# Generated by Django 2.1.5 on 2019-02-25 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kst.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('states', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_image', models.FileField(blank=True, null=True, upload_to=kst.models.upload_image_path_questions)),
                ('option1', models.CharField(blank=True, max_length=2200)),
                ('option2', models.CharField(blank=True, max_length=2200)),
                ('option3', models.CharField(blank=True, max_length=2200)),
                ('option4', models.CharField(blank=True, max_length=2200)),
                ('op1', models.BooleanField(default=False)),
                ('op2', models.BooleanField(default=False)),
                ('op3', models.BooleanField(default=False)),
                ('op4', models.BooleanField(default=False)),
                ('integer_type', models.BooleanField(default=False)),
                ('single_option', models.BooleanField(default=False)),
                ('integeral_answer', models.CharField(blank=True, max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.State')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dont_know_switch', models.BooleanField(default=0)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='states.Chapter')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='states.Node')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.State')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(blank=True, help_text=' Gives current question only if chapter is running currently ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kst.AssessmentQuestion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op1', models.BooleanField(default=False)),
                ('op2', models.BooleanField(default=False)),
                ('op3', models.BooleanField(default=False)),
                ('op4', models.BooleanField(default=False)),
                ('integer_type_submission', models.CharField(blank=True, max_length=200)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kst.AssessmentQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jump', models.IntegerField(default=0, help_text='1 means last question attempted was correct and -1 means incorrect and so on. 0 means null.')),
                ('score', models.IntegerField(default=0, help_text='To save score of student from question assessment session')),
                ('empty', models.BooleanField(default=False, help_text='Empty true if chapter have no state or no node')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='states.Chapter')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='states.Node')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='states.State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
