# Generated by Django 2.1.4 on 2019-03-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kst', '0002_auto_20190310_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentquestion',
            name='assess',
            field=models.BooleanField(default=False, help_text='True if assessment is finieshed for the user'),
        ),
        migrations.AddField(
            model_name='studentstatus',
            name='assess',
            field=models.IntegerField(default=0, help_text='If in assessment=0, if assessment learnt = 1, if assess=2 content learning active, then assessment of that learning =3'),
        ),
    ]
