# Generated by Django 2.1.4 on 2019-03-11 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kst', '0005_result_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1', models.IntegerField(default=0)),
                ('r2', models.IntegerField(default=0)),
                ('r3', models.IntegerField(default=0)),
                ('r4', models.IntegerField(default=0)),
                ('sr1', models.IntegerField(default=0)),
                ('sr2', models.IntegerField(default=0)),
                ('sr3', models.IntegerField(default=0)),
                ('sr4', models.IntegerField(default=0)),
                ('rr1', models.IntegerField(default=0)),
                ('rr2', models.IntegerField(default=0)),
                ('rr3', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
