# Generated by Django 2.1.4 on 2018-12-06 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapters', '0002_auto_20181206_1452'),
        ('userstates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedate', models.DateTimeField(auto_now_add=True, null=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chapters.Chapter')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_part', models.IntegerField(default=0, help_text='It is 0 for entering detail stage, 1 for assessment, 2 for report and 3 to begin learning and ending of assessment')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercurrentnode',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='usercurrentnode',
            name='node',
        ),
        migrations.RemoveField(
            model_name='usercurrentnode',
            name='user',
        ),
        migrations.AddField(
            model_name='tempactivenode',
            name='dont_know_switch',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='tempactivenode',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chapters.Chapter'),
        ),
        migrations.AlterField(
            model_name='tempactivenode',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='states.Node'),
        ),
        migrations.AlterField(
            model_name='tempactivenode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Proficiency',
        ),
        migrations.DeleteModel(
            name='UserCurrentNode',
        ),
    ]
